on:
  push:
    branches: ["master"]

env:
  PLATFORMS: linux/amd64,linux/arm/v7,linux/arm64

jobs:
  publish-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install poetry
      - run: poetry install
      - name: Log into Dockerhub
        uses: docker/login-action@v1
        with:
          username: assaflavie
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: make pypi push
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: ${{ env.PLATFORMS }}
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: assaflavie/runlike
          tags: |
            type=ref,event=branch
          # tag master as latest
          flavor: latest=${{ github.ref_name == 'master' }}
      - name: Log into Dockerhub
        uses: docker/login-action@v1
        with:
          username: assaflavie
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          pull: true
