on:
  push:
    branches: ["master"]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - run: pip install poetry
      - run: poetry install
      - run: docker login -u assaflavie -p "$DOCKERHUB_PASSWORD"
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      - run: make pypi push
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
